dataset:
  path: "/Users/swgj/Documents/Code/python_project/FinanceRAG/data"
  pdf:  "pdf"
  pdf2txt:  "pdf2txt"
  db: "博金杯比赛数据.db"
  question: "question.json"
  markdown: "markdown"

models:
  path: "/Users/swgj/Documents/Code/models"
  ner: "ner"
  sql: "sql"
  rag: "rag"
  embedding: "embedding"

lora:
  path: "/Users/swgj/Documents/Code/lora"
  ner: "ner"
  sql: "sql"

port: 5000