dataset:
  path: "/Users/swgj/Documents/Code/python_project/FinanceRAG/data"
  pdf:  "pdf"
  pdf2txt:  "pdf2txt"
  db: "博金杯比赛数据.db"
  question: "question.json"
  markdown: "markdown"
  preprocessed_md: "preprocessed_md"

models:
  path: "/Users/swgj/Documents/Code/python_project/FinanceRAG/models"
  ner: "ner"
  sql: "sql"
  rag: "qwen2.5"
  embedding: "bge-large-zh-v1.5"
  reranker: "bge-reranker-large"

lora:
  path: "/Users/swgj/Documents/Code/lora"
  ner: "ner"
  sql: "sql"

milvus:
  host: "localhost"
  port: 19530
  collection_name: "financeMD"
  uri: "/Users/swgj/Documents/Code/python_project/FinanceRAG/data/milvus_md.db"
  index_storage: "/Users/swgj/Documents/Code/python_project/FinanceRAG/data/milvus_md_index"

port: 5000